import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { SeverityBadge } from "@/components/common/SeverityBadge";
import { formatDateTime } from "@/utils/date";
export const AlertTable = ({ alerts, onAlertClick }) => {
    return (_jsx("div", { className: "border border-gray-700 rounded overflow-hidden", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-gray-800 border-b border-gray-700", children: [_jsx("th", { className: "px-4 py-3 text-left text-gray-300 font-semibold", children: "Severity" }), _jsx("th", { className: "px-4 py-3 text-left text-gray-300 font-semibold", children: "Event" }), _jsx("th", { className: "px-4 py-3 text-left text-gray-300 font-semibold", children: "Camera" }), _jsx("th", { className: "px-4 py-3 text-left text-gray-300 font-semibold", children: "Time" }), _jsx("th", { className: "px-4 py-3 text-left text-gray-300 font-semibold", children: "Confidence" }), _jsx("th", { className: "px-4 py-3 text-left text-gray-300 font-semibold", children: "Status" })] }) }), _jsx("tbody", { children: alerts.map((alert) => (_jsxs("tr", { className: "border-b border-gray-700 hover:bg-gray-800/50 transition cursor-pointer", onClick: () => onAlertClick?.(alert), children: [_jsx("td", { className: "px-4 py-3", children: _jsx(SeverityBadge, { severity: alert.severity }) }), _jsx("td", { className: "px-4 py-3 text-white", children: alert.eventType.replace(/_/g, " ") }), _jsx("td", { className: "px-4 py-3 text-gray-300", children: alert.cameraId }), _jsx("td", { className: "px-4 py-3 text-gray-400", children: formatDateTime(alert.timestamp) }), _jsxs("td", { className: "px-4 py-3 text-gray-300", children: [alert.confidence, "%"] }), _jsx("td", { className: "px-4 py-3", children: _jsx("span", { className: `px-2 py-1 rounded text-xs font-medium ${alert.status === "ACTIVE"
                                        ? "bg-red-900 text-red-200"
                                        : alert.status === "INVESTIGATING"
                                            ? "bg-yellow-900 text-yellow-200"
                                            : "bg-green-900 text-green-200"}`, children: alert.status }) })] }, alert.id))) })] }) }));
};
