import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { StatusBadge } from "@/components/common/StatusBadge";
import { AlertCircle, Users, Truck } from "lucide-react";
export const CameraGrid = ({ cameras, cameraStats = {} }) => {
    return (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4", children: cameras.map((camera) => {
            const stats = cameraStats[camera.id] || {};
            return (_jsxs(Link, { to: `/cameras/${camera.id}`, className: "border border-gray-700 rounded overflow-hidden hover:border-blue-500 transition group cursor-pointer", children: [_jsx("div", { className: "bg-gray-800 aspect-video flex items-center justify-center relative overflow-hidden group-hover:bg-gray-700 transition", children: _jsxs("div", { className: "text-gray-500 text-center", children: [_jsx("div", { className: "mb-2", children: "\uD83D\uDCF9" }), _jsx("div", { className: "text-xs text-gray-400", children: "Video Stream" })] }) }), _jsxs("div", { className: "p-3 bg-gray-900 border-t border-gray-700 space-y-2", children: [_jsxs("div", { children: [_jsx("p", { className: "text-white font-semibold text-sm", children: camera.name }), _jsx("p", { className: "text-gray-400 text-xs", children: camera.location })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(StatusBadge, { status: camera.status }), _jsxs("span", { className: "text-gray-400 text-xs", children: [camera.fps, " FPS"] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-2 pt-2 border-t border-gray-800", children: [_jsxs("div", { className: "flex items-center gap-1 text-xs", children: [_jsx(Users, { size: 12, className: "text-gray-500" }), _jsx("span", { className: "text-gray-300", children: stats.peopleCount || 0 })] }), _jsxs("div", { className: "flex items-center gap-1 text-xs", children: [_jsx(Truck, { size: 12, className: "text-gray-500" }), _jsx("span", { className: "text-gray-300", children: stats.vehicleCount || 0 })] })] }), stats.latestAlert && (_jsx("div", { className: "pt-2 border-t border-gray-800", children: _jsxs("div", { className: "flex items-center gap-1 text-xs", children: [_jsx(AlertCircle, { size: 12, className: "text-orange-400" }), _jsx("span", { className: "text-orange-300 truncate", children: stats.latestAlert.description })] }) }))] })] }, camera.id));
        }) }));
};
